#!/bin/bash

# check if all required packages are installed

for package in 'python-appindicator' 'python-crypto'
do
	dpkg -s $package &> /dev/null || \
	(
		echo "$package must be installed"
		sudo apt-get install $package
	)
done

python "$0.py" "$@"

while [[ $? == 2 ]]
do
	python "$0.py" "$@"
done
