#!/bin/bash

# this script will look at your nautilus sFTP bookmarks
# and add them to the bookmarks-indicator config

# find the working directory where this script is, and cd one level up
DIR=( `dirname "$(readlink -f "$0")"` )
cd "$DIR"
cd ..

# if sftp directory does not exists create it
mkdir -p "sftp"

# read through the sftp bookmarks and create an sftp script file for each one
cat "$HOME/.config/gtk-3.0/bookmarks" |\
grep "^sftp:" |\
while read sftp_address sftp_title
do
    # check if that bookmark file exists so we dont overwrite existing bookmarks
    if [ ! -f "sftp/$sftp_title.sftp" ]
    then
        # if not create it, add the command, and make sftp script executable
        touch "sftp/$sftp_title.sftp"
        echo "#!/bin/bash" >> "sftp/$sftp_title.sftp"
        echo "nautilus $sftp_title" >> "sftp/$sftp_title.sftp"
        chmod +x "sftp/$sftp_title.sftp"
    fi
done

# if config file doesn't have an "---sFTP" section, add it
if ! grep -q -- "---sFTP" "config"
then
      echo "---sFTP" >> "config"
fi

# check if bookmarks exist in config and add them if they do not
while read -r script_file_
do
    script_file=$(readlink -f "$script_file_")
    if ! grep -q "$script_file" "config"
    then
        echo "$script_file" >> "config"
    fi
done < <(find "./sftp" -maxdepth 1 -type f -name "*.sftp" | sort)
