name: builds

on: 
  push:
    branches:
    - master

jobs:
  
  build-debian-9:
    runs-on: ubuntu-latest

    steps:
    - uses: docker://debian:9
    - uses: actions/checkout@v2
      with:
        path: /tmp/bookmarks-indicator
    - run: sudo apt update
    - run: sudo apt -y install build-essential cmake libgtk-3-dev libgtkmm-3.0-dev
    - run: mkdir -p /tmp/bookmarks-indicator/build
    - run: cd /tmp/bookmarks-indicator/build
    - run: cmake .. && make && sudo make install 
