name: builds

on: 
  push:
    branches:
    - master

jobs:
  
  build-debian-9:
    runs-on: ubuntu-latest

    steps:
    - uses: docker://debian:9
    - uses: actions/checkout@v2
    - name: build
      run: |
        sudo apt update
        sudo apt -y install build-essential cmake libgtk-3-dev libgtkmm-3.0-dev
        pwd
        ls -al
        mkdir -p bookmarks-indicator/build
        cd bookmarks-indicator/build
        pwd
        ls -al
        cmake .. && make && sudo make install 
