name: builds

on: 
  push:
    branches:
    - master

jobs:
  
  build-debian-9:
    runs-on: ubuntu-latest

    steps:
    - uses: docker://debian:9
    - uses: actions/checkout@v2
    - run: pwd
    - run: sudo apt update
    - run: sudo apt -y install build-essential cmake libgtk-3-dev libgtkmm-3.0-dev
    - run: mkdir -p bookmarks-indicator/bookmarks-indicator/build
    - run: cd bookmarks-indicator/bookmarks-indicator/build
    - run: cmake .. && make && sudo make install 
