name: builds

on: 
  push:
    branches:
    - master

jobs:
  
  build-debian-9:
    runs-on: [ubuntu-latest]
    container: 
      image: debian:9
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        apt update
        apt -y install build-essential cmake libgtk-3-dev libgtkmm-3.0-dev
        mkdir build && cd build
        cmake .. && make && make install 
